default:
  target: duckdb
  outputs:
    duckdb:
      type: duckdb
      path: "jaffle_shop.duckdb"
      schema: public
      threads: 4

    duckdb-base:
      type: duckdb
      path: "jaffle_shop.duckdb"
      schema: base
      threads: 4

    duckdb-current:
      type: duckdb
      path: "jaffle_shop.duckdb"
      schema: current
      threads: 4

    snowflake:
      type: snowflake
      account: "{{ env_var('SNOWFLAKE_ACCOUNT', 'dummy_account') }}"
      user: "{{ env_var('SNOWFLAKE_USER', 'dummy_user') }}"
      password: "{{ env_var('SNOWFLAKE_PASSWORD', 'dummy_password') }}"
      role: "{{ env_var('SNOWFLAKE_ROLE', 'SYSADMIN') }}"
      warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE', 'COMPUTE_WH') }}"
      database: "{{ env_var('SNOWFLAKE_DATABASE', 'JAFFLE_SHOP') }}"
      schema: public
      threads: 4
